### PR TITLE
Ignore System.out.close calls so IntelliJ doesn't incorrectly mark tests as terminated

### LINKED ISSUE #94: Successful tests marked as "terminated" in IntelliJ
Hi,

I'm puzzled why I'm getting Tests passed: 0 but not explicitly failing from my tests when running via Idea. 

I made a simple pom and I seem to pass the examples in another project, but my custom tests aren't passing. It seems the assertions are as expected and the tables are created. Then for some reason some part of the test setup or annotations is not passing my tests. Can someone get me back on track?

Thanks
```
package com.test.scno.hiveunit.location;

import com.google.common.collect.Sets;
import com.klarna.hiverunner.HiveShell;
import com.klarna.hiverunner.StandaloneHiveRunner;
import com.klarna.hiverunner.annotations.HiveProperties;
import com.klarna.hiverunner.annotations.HiveResource;
import com.klarna.hiverunner.annotations.HiveRunnerSetup;
import com.klarna.hiverunner.annotations.HiveSQL;
import com.klarna.hiverunner.annotations.HiveSetupScript;
import com.klarna.hiverunner.config.HiveRunnerConfig;
import org.apache.commons.collections.MapUtils;
import org.junit.Assert;
import org.junit.Test;
import org.junit.runner.RunWith;

import java.io.File;
import java.util.HashMap;
import java.util.HashSet;
import java.util.List;
import java.util.Map;


@RunWith(StandaloneHiveRunner.class)
public class SomeTableTest {

    @HiveRunnerSetup
    public final HiveRunnerConfig CONFIG = new HiveRunnerConfig(){{
        setHiveExecutionEngine("tez");
    }};


    @HiveProperties
    public Map<String, String> hiveProperties = MapUtils.putAll(new HashMap(), new Object[]{
            "MY.HDFS.DIR", "${hadoop.tmp.dir}",
            "my.schema", "SOME_DB",
            "my.schema2", "ANOTHER_DB"
    });

    @HiveSetupScript
    private String createSchemaScript = "create schema ${hiveconf:my.schema}"+";" +"create schema ${hiveconf:my.schema2}";

    @HiveResource(targetFile = "${hiveconf:MY.HDFS.DIR}/data/in/data.gz")
    private File dataFromFile = new File(ClassLoader.getSystemResource("data/location/SOME_DB/SOME_TABLE/data.gz").getPath());


    @HiveSQL(files = {"schemas/hive/ANOTHER_DB/SOME_TABLE.sql"}, encoding = "UTF-8")
    private HiveShell hiveShell;

    @Test
    public void testTablesContainsItems() {
        List<String> sourceTableResult = hiveShell.executeQuery("SELECT * FROM SOME_DB.SOME_TABLE LIMIT 10");
        List<String> targetTableResult = hiveShell.executeQuery("SELECT * FROM ANOTHER_DB.ANOTHER_TABLE LIMIT 10");
        System.out.println(sourceTableResult.size());
        System.out.println(targetTableResult.size());
        Assert.assertTrue(sourceTableResult.size()==10);
        Assert.assertTrue(targetTableResult.size()==10);
    }
}
```

```
<?xml version="1.0"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <groupId>com.test.scno</groupId>
  <artifactId>scno-hive-unit</artifactId>
  <version>1.0.0</version>
  <name>${project.artifactId}</name>
  <properties>
   <hiverunner.version>4.0.0</hiverunner.version>
    <encoding>UTF-8</encoding>
    <junit.version>4.12</junit.version>
    <!-- Plugins -->
    <surefire.plugin.version>2.21.0</surefire.plugin.version>
    <maven.compiler.source>1.8</maven.compiler.source>
    <maven.compiler.target>1.8</maven.compiler.target>
  </properties>
  <dependencies>
    <dependency>
      <groupId>com.klarna</groupId>
      <artifactId>hiverunner</artifactId>
      <version>${hiverunner.version}</version>
     <scope>test</scope>
    </dependency>
    <dependency>
      <groupId>junit</groupId>
      <artifactId>junit</artifactId>
      <version>${junit.version}</version>
      <scope>test</scope>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-surefire-plugin</artifactId>
        <version>2.21.0</version>
        <configuration>
          <includes>
          </includes>
          <forkCount>1C</forkCount>
          <reuseForks>true</reuseForks>
          <argLine>-Xmx2048m -XX:MaxPermSize=512m</argLine>
          <systemProperties>
            <hiveconf_hive.execution.engine>tez</hiveconf_hive.execution.engine>
            <hiveconf_hive.exec.counters.pull.interval>1000</hiveconf_hive.exec.counters.pull.interval>
            <commandShellEmulator>BEELINE</commandShellEmulator>
            <enableTimeout>false</enableTimeout>
            <timeoutSeconds>30</timeoutSeconds>
            <timeoutRetries>2</timeoutRetries>
          </systemProperties>
        </configuration>
      </plugin>
      <plugin>
        <groupId>org.apache.maven.plugins</groupId>
        <artifactId>maven-compiler-plugin</artifactId>
        <version>3.7.0</version>
        <configuration>
          <source>${maven.compiler.source}</source>
          <target>${maven.compiler.target}</target>
        </configuration>
      </plugin>
    </plugins>
  </build>
</project>
```

### PR DESCRIPTION
**Pull request by massdosage**
Fixes #94

### CODE REVIEW

**Review by javsanbel2 — APPROVED** [review]

File: src/main/java/com/klarna/hiverunner/HiveServerContainer.java [hunk 1]
```diff
@@ -116,11 +118,14 @@ public Path getBaseDir() {
     }
 
     public List<Object[]> executeStatement(String hiveql) {
+        //this PrintStream hack can be removed if/when IntelliJ fixes https://youtrack.jetbrains.com/issue/IDEA-120628
+        //see https://github.com/klarna/HiveRunner/issues/94 for more info
```
Comment (JayGreeeen) [inline src/main/java/com/klarna/hiverunner/HiveServerContainer.java:122]:
```suggestion
        // This PrintStream hack can be removed if/when IntelliJ fixes https://youtrack.jetbrains.com/issue/IDEA-120628
        // See https://github.com/klarna/HiveRunner/issues/94 for more info.
```

**Review by JayGreeeen — APPROVED** [review]
